package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetCharactersCharacterIDAssetsOKCode is the HTTP code returned for type GetCharactersCharacterIDAssetsOK
const GetCharactersCharacterIDAssetsOKCode int = 200

/*GetCharactersCharacterIDAssetsOK A flat list of the users assets

swagger:response getCharactersCharacterIdAssetsOK
*/
type GetCharactersCharacterIDAssetsOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*
	  In: Body
	*/
	Payload models.GetCharactersCharacterIDAssetsOKBody `json:"body,omitempty"`
}

// NewGetCharactersCharacterIDAssetsOK creates GetCharactersCharacterIDAssetsOK with default headers values
func NewGetCharactersCharacterIDAssetsOK() *GetCharactersCharacterIDAssetsOK {
	return &GetCharactersCharacterIDAssetsOK{}
}

// WithCacheControl adds the cacheControl to the get characters character Id assets o k response
func (o *GetCharactersCharacterIDAssetsOK) WithCacheControl(cacheControl string) *GetCharactersCharacterIDAssetsOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get characters character Id assets o k response
func (o *GetCharactersCharacterIDAssetsOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get characters character Id assets o k response
func (o *GetCharactersCharacterIDAssetsOK) WithExpires(expires string) *GetCharactersCharacterIDAssetsOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get characters character Id assets o k response
func (o *GetCharactersCharacterIDAssetsOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get characters character Id assets o k response
func (o *GetCharactersCharacterIDAssetsOK) WithLastModified(lastModified string) *GetCharactersCharacterIDAssetsOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get characters character Id assets o k response
func (o *GetCharactersCharacterIDAssetsOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get characters character Id assets o k response
func (o *GetCharactersCharacterIDAssetsOK) WithPayload(payload models.GetCharactersCharacterIDAssetsOKBody) *GetCharactersCharacterIDAssetsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get characters character Id assets o k response
func (o *GetCharactersCharacterIDAssetsOK) SetPayload(payload models.GetCharactersCharacterIDAssetsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCharactersCharacterIDAssetsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetCharactersCharacterIDAssetsOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetCharactersCharacterIDAssetsForbiddenCode is the HTTP code returned for type GetCharactersCharacterIDAssetsForbidden
const GetCharactersCharacterIDAssetsForbiddenCode int = 403

/*GetCharactersCharacterIDAssetsForbidden Forbidden

swagger:response getCharactersCharacterIdAssetsForbidden
*/
type GetCharactersCharacterIDAssetsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GetCharactersCharacterIDAssetsForbiddenBody `json:"body,omitempty"`
}

// NewGetCharactersCharacterIDAssetsForbidden creates GetCharactersCharacterIDAssetsForbidden with default headers values
func NewGetCharactersCharacterIDAssetsForbidden() *GetCharactersCharacterIDAssetsForbidden {
	return &GetCharactersCharacterIDAssetsForbidden{}
}

// WithPayload adds the payload to the get characters character Id assets forbidden response
func (o *GetCharactersCharacterIDAssetsForbidden) WithPayload(payload *models.GetCharactersCharacterIDAssetsForbiddenBody) *GetCharactersCharacterIDAssetsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get characters character Id assets forbidden response
func (o *GetCharactersCharacterIDAssetsForbidden) SetPayload(payload *models.GetCharactersCharacterIDAssetsForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCharactersCharacterIDAssetsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCharactersCharacterIDAssetsInternalServerErrorCode is the HTTP code returned for type GetCharactersCharacterIDAssetsInternalServerError
const GetCharactersCharacterIDAssetsInternalServerErrorCode int = 500

/*GetCharactersCharacterIDAssetsInternalServerError Internal server error

swagger:response getCharactersCharacterIdAssetsInternalServerError
*/
type GetCharactersCharacterIDAssetsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetCharactersCharacterIDAssetsInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetCharactersCharacterIDAssetsInternalServerError creates GetCharactersCharacterIDAssetsInternalServerError with default headers values
func NewGetCharactersCharacterIDAssetsInternalServerError() *GetCharactersCharacterIDAssetsInternalServerError {
	return &GetCharactersCharacterIDAssetsInternalServerError{}
}

// WithPayload adds the payload to the get characters character Id assets internal server error response
func (o *GetCharactersCharacterIDAssetsInternalServerError) WithPayload(payload *models.GetCharactersCharacterIDAssetsInternalServerErrorBody) *GetCharactersCharacterIDAssetsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get characters character Id assets internal server error response
func (o *GetCharactersCharacterIDAssetsInternalServerError) SetPayload(payload *models.GetCharactersCharacterIDAssetsInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCharactersCharacterIDAssetsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
