package sovereignty

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetSovereigntyMapOKCode is the HTTP code returned for type GetSovereigntyMapOK
const GetSovereigntyMapOKCode int = 200

/*GetSovereigntyMapOK A list of sovereignty information for solar systems in New Eden

swagger:response getSovereigntyMapOK
*/
type GetSovereigntyMapOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*
	  In: Body
	*/
	Payload models.GetSovereigntyMapOKBody `json:"body,omitempty"`
}

// NewGetSovereigntyMapOK creates GetSovereigntyMapOK with default headers values
func NewGetSovereigntyMapOK() *GetSovereigntyMapOK {
	return &GetSovereigntyMapOK{}
}

// WithCacheControl adds the cacheControl to the get sovereignty map o k response
func (o *GetSovereigntyMapOK) WithCacheControl(cacheControl string) *GetSovereigntyMapOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get sovereignty map o k response
func (o *GetSovereigntyMapOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get sovereignty map o k response
func (o *GetSovereigntyMapOK) WithExpires(expires string) *GetSovereigntyMapOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get sovereignty map o k response
func (o *GetSovereigntyMapOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get sovereignty map o k response
func (o *GetSovereigntyMapOK) WithLastModified(lastModified string) *GetSovereigntyMapOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get sovereignty map o k response
func (o *GetSovereigntyMapOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get sovereignty map o k response
func (o *GetSovereigntyMapOK) WithPayload(payload models.GetSovereigntyMapOKBody) *GetSovereigntyMapOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sovereignty map o k response
func (o *GetSovereigntyMapOK) SetPayload(payload models.GetSovereigntyMapOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSovereigntyMapOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetSovereigntyMapOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetSovereigntyMapInternalServerErrorCode is the HTTP code returned for type GetSovereigntyMapInternalServerError
const GetSovereigntyMapInternalServerErrorCode int = 500

/*GetSovereigntyMapInternalServerError Internal server error

swagger:response getSovereigntyMapInternalServerError
*/
type GetSovereigntyMapInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetSovereigntyMapInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetSovereigntyMapInternalServerError creates GetSovereigntyMapInternalServerError with default headers values
func NewGetSovereigntyMapInternalServerError() *GetSovereigntyMapInternalServerError {
	return &GetSovereigntyMapInternalServerError{}
}

// WithPayload adds the payload to the get sovereignty map internal server error response
func (o *GetSovereigntyMapInternalServerError) WithPayload(payload *models.GetSovereigntyMapInternalServerErrorBody) *GetSovereigntyMapInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sovereignty map internal server error response
func (o *GetSovereigntyMapInternalServerError) SetPayload(payload *models.GetSovereigntyMapInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSovereigntyMapInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
