package sovereignty

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetSovereigntyCampaignsOKCode is the HTTP code returned for type GetSovereigntyCampaignsOK
const GetSovereigntyCampaignsOKCode int = 200

/*GetSovereigntyCampaignsOK A list of sovereignty campaigns

swagger:response getSovereigntyCampaignsOK
*/
type GetSovereigntyCampaignsOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*
	  In: Body
	*/
	Payload models.GetSovereigntyCampaignsOKBody `json:"body,omitempty"`
}

// NewGetSovereigntyCampaignsOK creates GetSovereigntyCampaignsOK with default headers values
func NewGetSovereigntyCampaignsOK() *GetSovereigntyCampaignsOK {
	return &GetSovereigntyCampaignsOK{}
}

// WithCacheControl adds the cacheControl to the get sovereignty campaigns o k response
func (o *GetSovereigntyCampaignsOK) WithCacheControl(cacheControl string) *GetSovereigntyCampaignsOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get sovereignty campaigns o k response
func (o *GetSovereigntyCampaignsOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get sovereignty campaigns o k response
func (o *GetSovereigntyCampaignsOK) WithExpires(expires string) *GetSovereigntyCampaignsOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get sovereignty campaigns o k response
func (o *GetSovereigntyCampaignsOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get sovereignty campaigns o k response
func (o *GetSovereigntyCampaignsOK) WithLastModified(lastModified string) *GetSovereigntyCampaignsOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get sovereignty campaigns o k response
func (o *GetSovereigntyCampaignsOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get sovereignty campaigns o k response
func (o *GetSovereigntyCampaignsOK) WithPayload(payload models.GetSovereigntyCampaignsOKBody) *GetSovereigntyCampaignsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sovereignty campaigns o k response
func (o *GetSovereigntyCampaignsOK) SetPayload(payload models.GetSovereigntyCampaignsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSovereigntyCampaignsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetSovereigntyCampaignsOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetSovereigntyCampaignsInternalServerErrorCode is the HTTP code returned for type GetSovereigntyCampaignsInternalServerError
const GetSovereigntyCampaignsInternalServerErrorCode int = 500

/*GetSovereigntyCampaignsInternalServerError Internal server error

swagger:response getSovereigntyCampaignsInternalServerError
*/
type GetSovereigntyCampaignsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetSovereigntyCampaignsInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetSovereigntyCampaignsInternalServerError creates GetSovereigntyCampaignsInternalServerError with default headers values
func NewGetSovereigntyCampaignsInternalServerError() *GetSovereigntyCampaignsInternalServerError {
	return &GetSovereigntyCampaignsInternalServerError{}
}

// WithPayload adds the payload to the get sovereignty campaigns internal server error response
func (o *GetSovereigntyCampaignsInternalServerError) WithPayload(payload *models.GetSovereigntyCampaignsInternalServerErrorBody) *GetSovereigntyCampaignsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sovereignty campaigns internal server error response
func (o *GetSovereigntyCampaignsInternalServerError) SetPayload(payload *models.GetSovereigntyCampaignsInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSovereigntyCampaignsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
