package status

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetStatusOKCode is the HTTP code returned for type GetStatusOK
const GetStatusOKCode int = 200

/*GetStatusOK Server status

swagger:response getStatusOK
*/
type GetStatusOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*
	  In: Body
	*/
	Payload *models.GetStatusOKBody `json:"body,omitempty"`
}

// NewGetStatusOK creates GetStatusOK with default headers values
func NewGetStatusOK() *GetStatusOK {
	return &GetStatusOK{}
}

// WithCacheControl adds the cacheControl to the get status o k response
func (o *GetStatusOK) WithCacheControl(cacheControl string) *GetStatusOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get status o k response
func (o *GetStatusOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get status o k response
func (o *GetStatusOK) WithExpires(expires string) *GetStatusOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get status o k response
func (o *GetStatusOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get status o k response
func (o *GetStatusOK) WithLastModified(lastModified string) *GetStatusOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get status o k response
func (o *GetStatusOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get status o k response
func (o *GetStatusOK) WithPayload(payload *models.GetStatusOKBody) *GetStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get status o k response
func (o *GetStatusOK) SetPayload(payload *models.GetStatusOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetStatusInternalServerErrorCode is the HTTP code returned for type GetStatusInternalServerError
const GetStatusInternalServerErrorCode int = 500

/*GetStatusInternalServerError Internal server error

swagger:response getStatusInternalServerError
*/
type GetStatusInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetStatusInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetStatusInternalServerError creates GetStatusInternalServerError with default headers values
func NewGetStatusInternalServerError() *GetStatusInternalServerError {
	return &GetStatusInternalServerError{}
}

// WithPayload adds the payload to the get status internal server error response
func (o *GetStatusInternalServerError) WithPayload(payload *models.GetStatusInternalServerErrorBody) *GetStatusInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get status internal server error response
func (o *GetStatusInternalServerError) SetPayload(payload *models.GetStatusInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
