package corporation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCorporationsNamesParams creates a new GetCorporationsNamesParams object
// with the default values initialized.
func NewGetCorporationsNamesParams() GetCorporationsNamesParams {
	var (
		datasourceDefault = string("tranquility")
	)
	return GetCorporationsNamesParams{
		Datasource: &datasourceDefault,
	}
}

// GetCorporationsNamesParams contains all the bound params for the get corporations names operation
// typically these are obtained from a http.Request
//
// swagger:parameters get_corporations_names
type GetCorporationsNamesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Client identifier, takes precedence over User-Agent
	  In: header
	*/
	XUserAgent *string
	/*A comma separated list of corporation IDs
	  Required: true
	  Max Items: 100
	  Min Items: 1
	  In: query
	*/
	CorporationIds []int64
	/*The server name you would like data from
	  In: query
	  Default: "tranquility"
	*/
	Datasource *string
	/*Client identifier, takes precedence over headers
	  In: query
	*/
	UserAgent *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetCorporationsNamesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if err := o.bindXUserAgent(r.Header[http.CanonicalHeaderKey("X-User-Agent")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	qCorporationIds, qhkCorporationIds, _ := qs.GetOK("corporation_ids")
	if err := o.bindCorporationIds(qCorporationIds, qhkCorporationIds, route.Formats); err != nil {
		res = append(res, err)
	}

	qDatasource, qhkDatasource, _ := qs.GetOK("datasource")
	if err := o.bindDatasource(qDatasource, qhkDatasource, route.Formats); err != nil {
		res = append(res, err)
	}

	qUserAgent, qhkUserAgent, _ := qs.GetOK("user_agent")
	if err := o.bindUserAgent(qUserAgent, qhkUserAgent, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCorporationsNamesParams) bindXUserAgent(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XUserAgent = &raw

	return nil
}

func (o *GetCorporationsNamesParams) bindCorporationIds(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("corporation_ids", "query")
	}

	var qvCorporationIds string
	if len(rawData) > 0 {
		qvCorporationIds = rawData[len(rawData)-1]
	}

	corporationIdsIC := swag.SplitByFormat(qvCorporationIds, "")

	if len(corporationIdsIC) == 0 {
		return errors.Required("corporation_ids", "query")
	}

	var corporationIdsIR []int64
	for i, corporationIdsIV := range corporationIdsIC {
		corporationIdsI, err := swag.ConvertInt64(corporationIdsIV)
		if err != nil {
			return errors.InvalidType(fmt.Sprintf("%s.%v", "corporation_ids", i), "query", "int64", corporationIdsI)
		}

		corporationIdsIR = append(corporationIdsIR, corporationIdsI)
	}

	o.CorporationIds = corporationIdsIR
	if err := o.validateCorporationIds(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetCorporationsNamesParams) validateCorporationIds(formats strfmt.Registry) error {

	corporationIdsSize := int64(len(o.CorporationIds))

	if err := validate.MinItems("corporation_ids", "query", corporationIdsSize, 1); err != nil {
		return err
	}

	if err := validate.MaxItems("corporation_ids", "query", corporationIdsSize, 100); err != nil {
		return err
	}

	return nil
}

func (o *GetCorporationsNamesParams) bindDatasource(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		var datasourceDefault string = string("tranquility")
		o.Datasource = &datasourceDefault
		return nil
	}

	o.Datasource = &raw

	if err := o.validateDatasource(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetCorporationsNamesParams) validateDatasource(formats strfmt.Registry) error {

	if err := validate.Enum("datasource", "query", *o.Datasource, []interface{}{"tranquility", "singularity"}); err != nil {
		return err
	}

	return nil
}

func (o *GetCorporationsNamesParams) bindUserAgent(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.UserAgent = &raw

	return nil
}
