package corporation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetCorporationsNamesOKCode is the HTTP code returned for type GetCorporationsNamesOK
const GetCorporationsNamesOKCode int = 200

/*GetCorporationsNamesOK List of id/name associations

swagger:response getCorporationsNamesOK
*/
type GetCorporationsNamesOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*
	  In: Body
	*/
	Payload models.GetCorporationsNamesOKBody `json:"body,omitempty"`
}

// NewGetCorporationsNamesOK creates GetCorporationsNamesOK with default headers values
func NewGetCorporationsNamesOK() *GetCorporationsNamesOK {
	return &GetCorporationsNamesOK{}
}

// WithCacheControl adds the cacheControl to the get corporations names o k response
func (o *GetCorporationsNamesOK) WithCacheControl(cacheControl string) *GetCorporationsNamesOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get corporations names o k response
func (o *GetCorporationsNamesOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get corporations names o k response
func (o *GetCorporationsNamesOK) WithExpires(expires string) *GetCorporationsNamesOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get corporations names o k response
func (o *GetCorporationsNamesOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get corporations names o k response
func (o *GetCorporationsNamesOK) WithLastModified(lastModified string) *GetCorporationsNamesOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get corporations names o k response
func (o *GetCorporationsNamesOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get corporations names o k response
func (o *GetCorporationsNamesOK) WithPayload(payload models.GetCorporationsNamesOKBody) *GetCorporationsNamesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get corporations names o k response
func (o *GetCorporationsNamesOK) SetPayload(payload models.GetCorporationsNamesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCorporationsNamesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetCorporationsNamesOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetCorporationsNamesInternalServerErrorCode is the HTTP code returned for type GetCorporationsNamesInternalServerError
const GetCorporationsNamesInternalServerErrorCode int = 500

/*GetCorporationsNamesInternalServerError Internal server error

swagger:response getCorporationsNamesInternalServerError
*/
type GetCorporationsNamesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetCorporationsNamesInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetCorporationsNamesInternalServerError creates GetCorporationsNamesInternalServerError with default headers values
func NewGetCorporationsNamesInternalServerError() *GetCorporationsNamesInternalServerError {
	return &GetCorporationsNamesInternalServerError{}
}

// WithPayload adds the payload to the get corporations names internal server error response
func (o *GetCorporationsNamesInternalServerError) WithPayload(payload *models.GetCorporationsNamesInternalServerErrorBody) *GetCorporationsNamesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get corporations names internal server error response
func (o *GetCorporationsNamesInternalServerError) SetPayload(payload *models.GetCorporationsNamesInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCorporationsNamesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
