package character

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCharactersCharacterIDBlueprintsHandlerFunc turns a function with the right signature into a get characters character id blueprints handler
type GetCharactersCharacterIDBlueprintsHandlerFunc func(GetCharactersCharacterIDBlueprintsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCharactersCharacterIDBlueprintsHandlerFunc) Handle(params GetCharactersCharacterIDBlueprintsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCharactersCharacterIDBlueprintsHandler interface for that can handle valid get characters character id blueprints params
type GetCharactersCharacterIDBlueprintsHandler interface {
	Handle(GetCharactersCharacterIDBlueprintsParams, interface{}) middleware.Responder
}

// NewGetCharactersCharacterIDBlueprints creates a new http.Handler for the get characters character id blueprints operation
func NewGetCharactersCharacterIDBlueprints(ctx *middleware.Context, handler GetCharactersCharacterIDBlueprintsHandler) *GetCharactersCharacterIDBlueprints {
	return &GetCharactersCharacterIDBlueprints{Context: ctx, Handler: handler}
}

/*GetCharactersCharacterIDBlueprints swagger:route GET /characters/{character_id}/blueprints/ Character getCharactersCharacterIdBlueprints

Get blueprints

Return a list of blueprints the character has

---

Alternate route: `/v1/characters/{character_id}/blueprints/`

Alternate route: `/legacy/characters/{character_id}/blueprints/`

Alternate route: `/dev/characters/{character_id}/blueprints/`


---

This route is cached for up to 3600 seconds

*/
type GetCharactersCharacterIDBlueprints struct {
	Context *middleware.Context
	Handler GetCharactersCharacterIDBlueprintsHandler
}

func (o *GetCharactersCharacterIDBlueprints) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetCharactersCharacterIDBlueprintsParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
