package character

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// PostCharactersAffiliationOKCode is the HTTP code returned for type PostCharactersAffiliationOK
const PostCharactersAffiliationOKCode int = 200

/*PostCharactersAffiliationOK Character corporation, alliance and faction IDs

swagger:response postCharactersAffiliationOK
*/
type PostCharactersAffiliationOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*
	  In: Body
	*/
	Payload models.PostCharactersAffiliationOKBody `json:"body,omitempty"`
}

// NewPostCharactersAffiliationOK creates PostCharactersAffiliationOK with default headers values
func NewPostCharactersAffiliationOK() *PostCharactersAffiliationOK {
	return &PostCharactersAffiliationOK{}
}

// WithCacheControl adds the cacheControl to the post characters affiliation o k response
func (o *PostCharactersAffiliationOK) WithCacheControl(cacheControl string) *PostCharactersAffiliationOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the post characters affiliation o k response
func (o *PostCharactersAffiliationOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the post characters affiliation o k response
func (o *PostCharactersAffiliationOK) WithExpires(expires string) *PostCharactersAffiliationOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the post characters affiliation o k response
func (o *PostCharactersAffiliationOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the post characters affiliation o k response
func (o *PostCharactersAffiliationOK) WithLastModified(lastModified string) *PostCharactersAffiliationOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the post characters affiliation o k response
func (o *PostCharactersAffiliationOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the post characters affiliation o k response
func (o *PostCharactersAffiliationOK) WithPayload(payload models.PostCharactersAffiliationOKBody) *PostCharactersAffiliationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post characters affiliation o k response
func (o *PostCharactersAffiliationOK) SetPayload(payload models.PostCharactersAffiliationOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCharactersAffiliationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.PostCharactersAffiliationOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// PostCharactersAffiliationUnprocessableEntityCode is the HTTP code returned for type PostCharactersAffiliationUnprocessableEntity
const PostCharactersAffiliationUnprocessableEntityCode int = 422

/*PostCharactersAffiliationUnprocessableEntity No valid character IDs found

swagger:response postCharactersAffiliationUnprocessableEntity
*/
type PostCharactersAffiliationUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.PostCharactersAffiliationUnprocessableEntityBody `json:"body,omitempty"`
}

// NewPostCharactersAffiliationUnprocessableEntity creates PostCharactersAffiliationUnprocessableEntity with default headers values
func NewPostCharactersAffiliationUnprocessableEntity() *PostCharactersAffiliationUnprocessableEntity {
	return &PostCharactersAffiliationUnprocessableEntity{}
}

// WithPayload adds the payload to the post characters affiliation unprocessable entity response
func (o *PostCharactersAffiliationUnprocessableEntity) WithPayload(payload *models.PostCharactersAffiliationUnprocessableEntityBody) *PostCharactersAffiliationUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post characters affiliation unprocessable entity response
func (o *PostCharactersAffiliationUnprocessableEntity) SetPayload(payload *models.PostCharactersAffiliationUnprocessableEntityBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCharactersAffiliationUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostCharactersAffiliationInternalServerErrorCode is the HTTP code returned for type PostCharactersAffiliationInternalServerError
const PostCharactersAffiliationInternalServerErrorCode int = 500

/*PostCharactersAffiliationInternalServerError Internal server error

swagger:response postCharactersAffiliationInternalServerError
*/
type PostCharactersAffiliationInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.PostCharactersAffiliationInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostCharactersAffiliationInternalServerError creates PostCharactersAffiliationInternalServerError with default headers values
func NewPostCharactersAffiliationInternalServerError() *PostCharactersAffiliationInternalServerError {
	return &PostCharactersAffiliationInternalServerError{}
}

// WithPayload adds the payload to the post characters affiliation internal server error response
func (o *PostCharactersAffiliationInternalServerError) WithPayload(payload *models.PostCharactersAffiliationInternalServerErrorBody) *PostCharactersAffiliationInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post characters affiliation internal server error response
func (o *PostCharactersAffiliationInternalServerError) SetPayload(payload *models.PostCharactersAffiliationInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCharactersAffiliationInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
