package loyalty

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetLoyaltyStoresCorporationIDOffersOKCode is the HTTP code returned for type GetLoyaltyStoresCorporationIDOffersOK
const GetLoyaltyStoresCorporationIDOffersOKCode int = 200

/*GetLoyaltyStoresCorporationIDOffersOK A list of offers

swagger:response getLoyaltyStoresCorporationIdOffersOK
*/
type GetLoyaltyStoresCorporationIDOffersOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*
	  In: Body
	*/
	Payload models.GetLoyaltyStoresCorporationIDOffersOKBody `json:"body,omitempty"`
}

// NewGetLoyaltyStoresCorporationIDOffersOK creates GetLoyaltyStoresCorporationIDOffersOK with default headers values
func NewGetLoyaltyStoresCorporationIDOffersOK() *GetLoyaltyStoresCorporationIDOffersOK {
	return &GetLoyaltyStoresCorporationIDOffersOK{}
}

// WithCacheControl adds the cacheControl to the get loyalty stores corporation Id offers o k response
func (o *GetLoyaltyStoresCorporationIDOffersOK) WithCacheControl(cacheControl string) *GetLoyaltyStoresCorporationIDOffersOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get loyalty stores corporation Id offers o k response
func (o *GetLoyaltyStoresCorporationIDOffersOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get loyalty stores corporation Id offers o k response
func (o *GetLoyaltyStoresCorporationIDOffersOK) WithExpires(expires string) *GetLoyaltyStoresCorporationIDOffersOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get loyalty stores corporation Id offers o k response
func (o *GetLoyaltyStoresCorporationIDOffersOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get loyalty stores corporation Id offers o k response
func (o *GetLoyaltyStoresCorporationIDOffersOK) WithLastModified(lastModified string) *GetLoyaltyStoresCorporationIDOffersOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get loyalty stores corporation Id offers o k response
func (o *GetLoyaltyStoresCorporationIDOffersOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get loyalty stores corporation Id offers o k response
func (o *GetLoyaltyStoresCorporationIDOffersOK) WithPayload(payload models.GetLoyaltyStoresCorporationIDOffersOKBody) *GetLoyaltyStoresCorporationIDOffersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get loyalty stores corporation Id offers o k response
func (o *GetLoyaltyStoresCorporationIDOffersOK) SetPayload(payload models.GetLoyaltyStoresCorporationIDOffersOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoyaltyStoresCorporationIDOffersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetLoyaltyStoresCorporationIDOffersOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetLoyaltyStoresCorporationIDOffersInternalServerErrorCode is the HTTP code returned for type GetLoyaltyStoresCorporationIDOffersInternalServerError
const GetLoyaltyStoresCorporationIDOffersInternalServerErrorCode int = 500

/*GetLoyaltyStoresCorporationIDOffersInternalServerError Internal server error

swagger:response getLoyaltyStoresCorporationIdOffersInternalServerError
*/
type GetLoyaltyStoresCorporationIDOffersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetLoyaltyStoresCorporationIDOffersInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetLoyaltyStoresCorporationIDOffersInternalServerError creates GetLoyaltyStoresCorporationIDOffersInternalServerError with default headers values
func NewGetLoyaltyStoresCorporationIDOffersInternalServerError() *GetLoyaltyStoresCorporationIDOffersInternalServerError {
	return &GetLoyaltyStoresCorporationIDOffersInternalServerError{}
}

// WithPayload adds the payload to the get loyalty stores corporation Id offers internal server error response
func (o *GetLoyaltyStoresCorporationIDOffersInternalServerError) WithPayload(payload *models.GetLoyaltyStoresCorporationIDOffersInternalServerErrorBody) *GetLoyaltyStoresCorporationIDOffersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get loyalty stores corporation Id offers internal server error response
func (o *GetLoyaltyStoresCorporationIDOffersInternalServerError) SetPayload(payload *models.GetLoyaltyStoresCorporationIDOffersInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoyaltyStoresCorporationIDOffersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
