package location

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCharactersCharacterIDLocationHandlerFunc turns a function with the right signature into a get characters character id location handler
type GetCharactersCharacterIDLocationHandlerFunc func(GetCharactersCharacterIDLocationParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCharactersCharacterIDLocationHandlerFunc) Handle(params GetCharactersCharacterIDLocationParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCharactersCharacterIDLocationHandler interface for that can handle valid get characters character id location params
type GetCharactersCharacterIDLocationHandler interface {
	Handle(GetCharactersCharacterIDLocationParams, interface{}) middleware.Responder
}

// NewGetCharactersCharacterIDLocation creates a new http.Handler for the get characters character id location operation
func NewGetCharactersCharacterIDLocation(ctx *middleware.Context, handler GetCharactersCharacterIDLocationHandler) *GetCharactersCharacterIDLocation {
	return &GetCharactersCharacterIDLocation{Context: ctx, Handler: handler}
}

/*GetCharactersCharacterIDLocation swagger:route GET /characters/{character_id}/location/ Location getCharactersCharacterIdLocation

Get character location

Information about the characters current location. Returns the current solar system id, and also the current station or structure ID if applicable.

---

Alternate route: `/v1/characters/{character_id}/location/`

Alternate route: `/legacy/characters/{character_id}/location/`

Alternate route: `/dev/characters/{character_id}/location/`


---

This route is cached for up to 5 seconds

*/
type GetCharactersCharacterIDLocation struct {
	Context *middleware.Context
	Handler GetCharactersCharacterIDLocationHandler
}

func (o *GetCharactersCharacterIDLocation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetCharactersCharacterIDLocationParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
