package planetary_interaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetCharactersCharacterIDPlanetsPlanetIDOKCode is the HTTP code returned for type GetCharactersCharacterIDPlanetsPlanetIDOK
const GetCharactersCharacterIDPlanetsPlanetIDOKCode int = 200

/*GetCharactersCharacterIDPlanetsPlanetIDOK Colony layout

swagger:response getCharactersCharacterIdPlanetsPlanetIdOK
*/
type GetCharactersCharacterIDPlanetsPlanetIDOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*
	  In: Body
	*/
	Payload *models.GetCharactersCharacterIDPlanetsPlanetIDOKBody `json:"body,omitempty"`
}

// NewGetCharactersCharacterIDPlanetsPlanetIDOK creates GetCharactersCharacterIDPlanetsPlanetIDOK with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDOK() *GetCharactersCharacterIDPlanetsPlanetIDOK {
	return &GetCharactersCharacterIDPlanetsPlanetIDOK{}
}

// WithCacheControl adds the cacheControl to the get characters character Id planets planet Id o k response
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) WithCacheControl(cacheControl string) *GetCharactersCharacterIDPlanetsPlanetIDOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get characters character Id planets planet Id o k response
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get characters character Id planets planet Id o k response
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) WithExpires(expires string) *GetCharactersCharacterIDPlanetsPlanetIDOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get characters character Id planets planet Id o k response
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get characters character Id planets planet Id o k response
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) WithLastModified(lastModified string) *GetCharactersCharacterIDPlanetsPlanetIDOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get characters character Id planets planet Id o k response
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get characters character Id planets planet Id o k response
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) WithPayload(payload *models.GetCharactersCharacterIDPlanetsPlanetIDOKBody) *GetCharactersCharacterIDPlanetsPlanetIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get characters character Id planets planet Id o k response
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) SetPayload(payload *models.GetCharactersCharacterIDPlanetsPlanetIDOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCharactersCharacterIDPlanetsPlanetIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCharactersCharacterIDPlanetsPlanetIDForbiddenCode is the HTTP code returned for type GetCharactersCharacterIDPlanetsPlanetIDForbidden
const GetCharactersCharacterIDPlanetsPlanetIDForbiddenCode int = 403

/*GetCharactersCharacterIDPlanetsPlanetIDForbidden Forbidden

swagger:response getCharactersCharacterIdPlanetsPlanetIdForbidden
*/
type GetCharactersCharacterIDPlanetsPlanetIDForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GetCharactersCharacterIDPlanetsPlanetIDForbiddenBody `json:"body,omitempty"`
}

// NewGetCharactersCharacterIDPlanetsPlanetIDForbidden creates GetCharactersCharacterIDPlanetsPlanetIDForbidden with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDForbidden() *GetCharactersCharacterIDPlanetsPlanetIDForbidden {
	return &GetCharactersCharacterIDPlanetsPlanetIDForbidden{}
}

// WithPayload adds the payload to the get characters character Id planets planet Id forbidden response
func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) WithPayload(payload *models.GetCharactersCharacterIDPlanetsPlanetIDForbiddenBody) *GetCharactersCharacterIDPlanetsPlanetIDForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get characters character Id planets planet Id forbidden response
func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) SetPayload(payload *models.GetCharactersCharacterIDPlanetsPlanetIDForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCharactersCharacterIDPlanetsPlanetIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCharactersCharacterIDPlanetsPlanetIDNotFoundCode is the HTTP code returned for type GetCharactersCharacterIDPlanetsPlanetIDNotFound
const GetCharactersCharacterIDPlanetsPlanetIDNotFoundCode int = 404

/*GetCharactersCharacterIDPlanetsPlanetIDNotFound Colony not found

swagger:response getCharactersCharacterIdPlanetsPlanetIdNotFound
*/
type GetCharactersCharacterIDPlanetsPlanetIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody `json:"body,omitempty"`
}

// NewGetCharactersCharacterIDPlanetsPlanetIDNotFound creates GetCharactersCharacterIDPlanetsPlanetIDNotFound with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDNotFound() *GetCharactersCharacterIDPlanetsPlanetIDNotFound {
	return &GetCharactersCharacterIDPlanetsPlanetIDNotFound{}
}

// WithPayload adds the payload to the get characters character Id planets planet Id not found response
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) WithPayload(payload *models.GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody) *GetCharactersCharacterIDPlanetsPlanetIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get characters character Id planets planet Id not found response
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) SetPayload(payload *models.GetCharactersCharacterIDPlanetsPlanetIDNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCharactersCharacterIDPlanetsPlanetIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCharactersCharacterIDPlanetsPlanetIDInternalServerErrorCode is the HTTP code returned for type GetCharactersCharacterIDPlanetsPlanetIDInternalServerError
const GetCharactersCharacterIDPlanetsPlanetIDInternalServerErrorCode int = 500

/*GetCharactersCharacterIDPlanetsPlanetIDInternalServerError Internal server error

swagger:response getCharactersCharacterIdPlanetsPlanetIdInternalServerError
*/
type GetCharactersCharacterIDPlanetsPlanetIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetCharactersCharacterIDPlanetsPlanetIDInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetCharactersCharacterIDPlanetsPlanetIDInternalServerError creates GetCharactersCharacterIDPlanetsPlanetIDInternalServerError with default headers values
func NewGetCharactersCharacterIDPlanetsPlanetIDInternalServerError() *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError {
	return &GetCharactersCharacterIDPlanetsPlanetIDInternalServerError{}
}

// WithPayload adds the payload to the get characters character Id planets planet Id internal server error response
func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) WithPayload(payload *models.GetCharactersCharacterIDPlanetsPlanetIDInternalServerErrorBody) *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get characters character Id planets planet Id internal server error response
func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) SetPayload(payload *models.GetCharactersCharacterIDPlanetsPlanetIDInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCharactersCharacterIDPlanetsPlanetIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
