package fittings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// PostCharactersCharacterIDFittingsCreatedCode is the HTTP code returned for type PostCharactersCharacterIDFittingsCreated
const PostCharactersCharacterIDFittingsCreatedCode int = 201

/*PostCharactersCharacterIDFittingsCreated A list of fittings

swagger:response postCharactersCharacterIdFittingsCreated
*/
type PostCharactersCharacterIDFittingsCreated struct {

	/*
	  In: Body
	*/
	Payload *models.PostCharactersCharacterIDFittingsCreatedBody `json:"body,omitempty"`
}

// NewPostCharactersCharacterIDFittingsCreated creates PostCharactersCharacterIDFittingsCreated with default headers values
func NewPostCharactersCharacterIDFittingsCreated() *PostCharactersCharacterIDFittingsCreated {
	return &PostCharactersCharacterIDFittingsCreated{}
}

// WithPayload adds the payload to the post characters character Id fittings created response
func (o *PostCharactersCharacterIDFittingsCreated) WithPayload(payload *models.PostCharactersCharacterIDFittingsCreatedBody) *PostCharactersCharacterIDFittingsCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post characters character Id fittings created response
func (o *PostCharactersCharacterIDFittingsCreated) SetPayload(payload *models.PostCharactersCharacterIDFittingsCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCharactersCharacterIDFittingsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostCharactersCharacterIDFittingsForbiddenCode is the HTTP code returned for type PostCharactersCharacterIDFittingsForbidden
const PostCharactersCharacterIDFittingsForbiddenCode int = 403

/*PostCharactersCharacterIDFittingsForbidden Forbidden

swagger:response postCharactersCharacterIdFittingsForbidden
*/
type PostCharactersCharacterIDFittingsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.PostCharactersCharacterIDFittingsForbiddenBody `json:"body,omitempty"`
}

// NewPostCharactersCharacterIDFittingsForbidden creates PostCharactersCharacterIDFittingsForbidden with default headers values
func NewPostCharactersCharacterIDFittingsForbidden() *PostCharactersCharacterIDFittingsForbidden {
	return &PostCharactersCharacterIDFittingsForbidden{}
}

// WithPayload adds the payload to the post characters character Id fittings forbidden response
func (o *PostCharactersCharacterIDFittingsForbidden) WithPayload(payload *models.PostCharactersCharacterIDFittingsForbiddenBody) *PostCharactersCharacterIDFittingsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post characters character Id fittings forbidden response
func (o *PostCharactersCharacterIDFittingsForbidden) SetPayload(payload *models.PostCharactersCharacterIDFittingsForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCharactersCharacterIDFittingsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostCharactersCharacterIDFittingsInternalServerErrorCode is the HTTP code returned for type PostCharactersCharacterIDFittingsInternalServerError
const PostCharactersCharacterIDFittingsInternalServerErrorCode int = 500

/*PostCharactersCharacterIDFittingsInternalServerError Internal server error

swagger:response postCharactersCharacterIdFittingsInternalServerError
*/
type PostCharactersCharacterIDFittingsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.PostCharactersCharacterIDFittingsInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostCharactersCharacterIDFittingsInternalServerError creates PostCharactersCharacterIDFittingsInternalServerError with default headers values
func NewPostCharactersCharacterIDFittingsInternalServerError() *PostCharactersCharacterIDFittingsInternalServerError {
	return &PostCharactersCharacterIDFittingsInternalServerError{}
}

// WithPayload adds the payload to the post characters character Id fittings internal server error response
func (o *PostCharactersCharacterIDFittingsInternalServerError) WithPayload(payload *models.PostCharactersCharacterIDFittingsInternalServerErrorBody) *PostCharactersCharacterIDFittingsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post characters character Id fittings internal server error response
func (o *PostCharactersCharacterIDFittingsInternalServerError) SetPayload(payload *models.PostCharactersCharacterIDFittingsInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostCharactersCharacterIDFittingsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
