package universe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetUniverseStructuresOKCode is the HTTP code returned for type GetUniverseStructuresOK
const GetUniverseStructuresOKCode int = 200

/*GetUniverseStructuresOK List of public structure IDs

swagger:response getUniverseStructuresOK
*/
type GetUniverseStructuresOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*200 ok array
	  Max Items: 10000
	  Unique: true
	  In: Body
	*/
	Payload []*int64 `json:"body,omitempty"`
}

// NewGetUniverseStructuresOK creates GetUniverseStructuresOK with default headers values
func NewGetUniverseStructuresOK() *GetUniverseStructuresOK {
	return &GetUniverseStructuresOK{}
}

// WithCacheControl adds the cacheControl to the get universe structures o k response
func (o *GetUniverseStructuresOK) WithCacheControl(cacheControl string) *GetUniverseStructuresOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get universe structures o k response
func (o *GetUniverseStructuresOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get universe structures o k response
func (o *GetUniverseStructuresOK) WithExpires(expires string) *GetUniverseStructuresOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get universe structures o k response
func (o *GetUniverseStructuresOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get universe structures o k response
func (o *GetUniverseStructuresOK) WithLastModified(lastModified string) *GetUniverseStructuresOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get universe structures o k response
func (o *GetUniverseStructuresOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get universe structures o k response
func (o *GetUniverseStructuresOK) WithPayload(payload []*int64) *GetUniverseStructuresOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get universe structures o k response
func (o *GetUniverseStructuresOK) SetPayload(payload []*int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUniverseStructuresOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*int64, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetUniverseStructuresInternalServerErrorCode is the HTTP code returned for type GetUniverseStructuresInternalServerError
const GetUniverseStructuresInternalServerErrorCode int = 500

/*GetUniverseStructuresInternalServerError Internal server error

swagger:response getUniverseStructuresInternalServerError
*/
type GetUniverseStructuresInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetUniverseStructuresInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetUniverseStructuresInternalServerError creates GetUniverseStructuresInternalServerError with default headers values
func NewGetUniverseStructuresInternalServerError() *GetUniverseStructuresInternalServerError {
	return &GetUniverseStructuresInternalServerError{}
}

// WithPayload adds the payload to the get universe structures internal server error response
func (o *GetUniverseStructuresInternalServerError) WithPayload(payload *models.GetUniverseStructuresInternalServerErrorBody) *GetUniverseStructuresInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get universe structures internal server error response
func (o *GetUniverseStructuresInternalServerError) SetPayload(payload *models.GetUniverseStructuresInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUniverseStructuresInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
