package universe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetUniverseSystemJumpsOKCode is the HTTP code returned for type GetUniverseSystemJumpsOK
const GetUniverseSystemJumpsOKCode int = 200

/*GetUniverseSystemJumpsOK A list of systems and number of jumps

swagger:response getUniverseSystemJumpsOK
*/
type GetUniverseSystemJumpsOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*
	  In: Body
	*/
	Payload models.GetUniverseSystemJumpsOKBody `json:"body,omitempty"`
}

// NewGetUniverseSystemJumpsOK creates GetUniverseSystemJumpsOK with default headers values
func NewGetUniverseSystemJumpsOK() *GetUniverseSystemJumpsOK {
	return &GetUniverseSystemJumpsOK{}
}

// WithCacheControl adds the cacheControl to the get universe system jumps o k response
func (o *GetUniverseSystemJumpsOK) WithCacheControl(cacheControl string) *GetUniverseSystemJumpsOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get universe system jumps o k response
func (o *GetUniverseSystemJumpsOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get universe system jumps o k response
func (o *GetUniverseSystemJumpsOK) WithExpires(expires string) *GetUniverseSystemJumpsOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get universe system jumps o k response
func (o *GetUniverseSystemJumpsOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get universe system jumps o k response
func (o *GetUniverseSystemJumpsOK) WithLastModified(lastModified string) *GetUniverseSystemJumpsOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get universe system jumps o k response
func (o *GetUniverseSystemJumpsOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get universe system jumps o k response
func (o *GetUniverseSystemJumpsOK) WithPayload(payload models.GetUniverseSystemJumpsOKBody) *GetUniverseSystemJumpsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get universe system jumps o k response
func (o *GetUniverseSystemJumpsOK) SetPayload(payload models.GetUniverseSystemJumpsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUniverseSystemJumpsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.GetUniverseSystemJumpsOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetUniverseSystemJumpsInternalServerErrorCode is the HTTP code returned for type GetUniverseSystemJumpsInternalServerError
const GetUniverseSystemJumpsInternalServerErrorCode int = 500

/*GetUniverseSystemJumpsInternalServerError Internal server error

swagger:response getUniverseSystemJumpsInternalServerError
*/
type GetUniverseSystemJumpsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetUniverseSystemJumpsInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetUniverseSystemJumpsInternalServerError creates GetUniverseSystemJumpsInternalServerError with default headers values
func NewGetUniverseSystemJumpsInternalServerError() *GetUniverseSystemJumpsInternalServerError {
	return &GetUniverseSystemJumpsInternalServerError{}
}

// WithPayload adds the payload to the get universe system jumps internal server error response
func (o *GetUniverseSystemJumpsInternalServerError) WithPayload(payload *models.GetUniverseSystemJumpsInternalServerErrorBody) *GetUniverseSystemJumpsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get universe system jumps internal server error response
func (o *GetUniverseSystemJumpsInternalServerError) SetPayload(payload *models.GetUniverseSystemJumpsInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUniverseSystemJumpsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
