package universe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// GetUniverseConstellationsOKCode is the HTTP code returned for type GetUniverseConstellationsOK
const GetUniverseConstellationsOKCode int = 200

/*GetUniverseConstellationsOK A list of constellation ids

swagger:response getUniverseConstellationsOK
*/
type GetUniverseConstellationsOK struct {
	/*The caching mechanism used
	  Required: true
	*/
	CacheControl string `json:"Cache-Control"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	Expires string `json:"Expires"`
	/*RFC7231 formatted datetime string
	  Required: true
	*/
	LastModified string `json:"Last-Modified"`

	/*200 ok array
	  Max Items: 10000
	  In: Body
	*/
	Payload []int32 `json:"body,omitempty"`
}

// NewGetUniverseConstellationsOK creates GetUniverseConstellationsOK with default headers values
func NewGetUniverseConstellationsOK() *GetUniverseConstellationsOK {
	return &GetUniverseConstellationsOK{}
}

// WithCacheControl adds the cacheControl to the get universe constellations o k response
func (o *GetUniverseConstellationsOK) WithCacheControl(cacheControl string) *GetUniverseConstellationsOK {
	o.CacheControl = cacheControl
	return o
}

// SetCacheControl sets the cacheControl to the get universe constellations o k response
func (o *GetUniverseConstellationsOK) SetCacheControl(cacheControl string) {
	o.CacheControl = cacheControl
}

// WithExpires adds the expires to the get universe constellations o k response
func (o *GetUniverseConstellationsOK) WithExpires(expires string) *GetUniverseConstellationsOK {
	o.Expires = expires
	return o
}

// SetExpires sets the expires to the get universe constellations o k response
func (o *GetUniverseConstellationsOK) SetExpires(expires string) {
	o.Expires = expires
}

// WithLastModified adds the lastModified to the get universe constellations o k response
func (o *GetUniverseConstellationsOK) WithLastModified(lastModified string) *GetUniverseConstellationsOK {
	o.LastModified = lastModified
	return o
}

// SetLastModified sets the lastModified to the get universe constellations o k response
func (o *GetUniverseConstellationsOK) SetLastModified(lastModified string) {
	o.LastModified = lastModified
}

// WithPayload adds the payload to the get universe constellations o k response
func (o *GetUniverseConstellationsOK) WithPayload(payload []int32) *GetUniverseConstellationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get universe constellations o k response
func (o *GetUniverseConstellationsOK) SetPayload(payload []int32) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUniverseConstellationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Cache-Control

	cacheControl := o.CacheControl
	if cacheControl != "" {
		rw.Header().Set("Cache-Control", cacheControl)
	}

	// response header Expires

	expires := o.Expires
	if expires != "" {
		rw.Header().Set("Expires", expires)
	}

	// response header Last-Modified

	lastModified := o.LastModified
	if lastModified != "" {
		rw.Header().Set("Last-Modified", lastModified)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]int32, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetUniverseConstellationsInternalServerErrorCode is the HTTP code returned for type GetUniverseConstellationsInternalServerError
const GetUniverseConstellationsInternalServerErrorCode int = 500

/*GetUniverseConstellationsInternalServerError Internal server error

swagger:response getUniverseConstellationsInternalServerError
*/
type GetUniverseConstellationsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.GetUniverseConstellationsInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetUniverseConstellationsInternalServerError creates GetUniverseConstellationsInternalServerError with default headers values
func NewGetUniverseConstellationsInternalServerError() *GetUniverseConstellationsInternalServerError {
	return &GetUniverseConstellationsInternalServerError{}
}

// WithPayload adds the payload to the get universe constellations internal server error response
func (o *GetUniverseConstellationsInternalServerError) WithPayload(payload *models.GetUniverseConstellationsInternalServerErrorBody) *GetUniverseConstellationsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get universe constellations internal server error response
func (o *GetUniverseConstellationsInternalServerError) SetPayload(payload *models.GetUniverseConstellationsInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUniverseConstellationsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
