package fleets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// DeleteFleetsFleetIDSquadsSquadIDURL generates an URL for the delete fleets fleet id squads squad id operation
type DeleteFleetsFleetIDSquadsSquadIDURL struct {
	FleetID int64
	SquadID int64

	Datasource *string
	Token      *string
	UserAgent  *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteFleetsFleetIDSquadsSquadIDURL) WithBasePath(bp string) *DeleteFleetsFleetIDSquadsSquadIDURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteFleetsFleetIDSquadsSquadIDURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteFleetsFleetIDSquadsSquadIDURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/fleets/{fleet_id}/squads/{squad_id}/"

	fleetID := swag.FormatInt64(o.FleetID)
	if fleetID != "" {
		_path = strings.Replace(_path, "{fleet_id}", fleetID, -1)
	} else {
		return nil, errors.New("FleetID is required on DeleteFleetsFleetIDSquadsSquadIDURL")
	}
	squadID := swag.FormatInt64(o.SquadID)
	if squadID != "" {
		_path = strings.Replace(_path, "{squad_id}", squadID, -1)
	} else {
		return nil, errors.New("SquadID is required on DeleteFleetsFleetIDSquadsSquadIDURL")
	}
	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/latest"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var datasource string
	if o.Datasource != nil {
		datasource = *o.Datasource
	}
	if datasource != "" {
		qs.Set("datasource", datasource)
	}

	var token string
	if o.Token != nil {
		token = *o.Token
	}
	if token != "" {
		qs.Set("token", token)
	}

	var userAgent string
	if o.UserAgent != nil {
		userAgent = *o.UserAgent
	}
	if userAgent != "" {
		qs.Set("user_agent", userAgent)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteFleetsFleetIDSquadsSquadIDURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteFleetsFleetIDSquadsSquadIDURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteFleetsFleetIDSquadsSquadIDURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteFleetsFleetIDSquadsSquadIDURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteFleetsFleetIDSquadsSquadIDURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteFleetsFleetIDSquadsSquadIDURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
