package fleets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// PostFleetsFleetIDMembersNoContentCode is the HTTP code returned for type PostFleetsFleetIDMembersNoContent
const PostFleetsFleetIDMembersNoContentCode int = 204

/*PostFleetsFleetIDMembersNoContent Fleet invitation sent

swagger:response postFleetsFleetIdMembersNoContent
*/
type PostFleetsFleetIDMembersNoContent struct {
}

// NewPostFleetsFleetIDMembersNoContent creates PostFleetsFleetIDMembersNoContent with default headers values
func NewPostFleetsFleetIDMembersNoContent() *PostFleetsFleetIDMembersNoContent {
	return &PostFleetsFleetIDMembersNoContent{}
}

// WriteResponse to the client
func (o *PostFleetsFleetIDMembersNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// PostFleetsFleetIDMembersForbiddenCode is the HTTP code returned for type PostFleetsFleetIDMembersForbidden
const PostFleetsFleetIDMembersForbiddenCode int = 403

/*PostFleetsFleetIDMembersForbidden Forbidden

swagger:response postFleetsFleetIdMembersForbidden
*/
type PostFleetsFleetIDMembersForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.PostFleetsFleetIDMembersForbiddenBody `json:"body,omitempty"`
}

// NewPostFleetsFleetIDMembersForbidden creates PostFleetsFleetIDMembersForbidden with default headers values
func NewPostFleetsFleetIDMembersForbidden() *PostFleetsFleetIDMembersForbidden {
	return &PostFleetsFleetIDMembersForbidden{}
}

// WithPayload adds the payload to the post fleets fleet Id members forbidden response
func (o *PostFleetsFleetIDMembersForbidden) WithPayload(payload *models.PostFleetsFleetIDMembersForbiddenBody) *PostFleetsFleetIDMembersForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post fleets fleet Id members forbidden response
func (o *PostFleetsFleetIDMembersForbidden) SetPayload(payload *models.PostFleetsFleetIDMembersForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFleetsFleetIDMembersForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFleetsFleetIDMembersNotFoundCode is the HTTP code returned for type PostFleetsFleetIDMembersNotFound
const PostFleetsFleetIDMembersNotFoundCode int = 404

/*PostFleetsFleetIDMembersNotFound The fleet does not exist or you don't have access to it

swagger:response postFleetsFleetIdMembersNotFound
*/
type PostFleetsFleetIDMembersNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.PostFleetsFleetIDMembersNotFoundBody `json:"body,omitempty"`
}

// NewPostFleetsFleetIDMembersNotFound creates PostFleetsFleetIDMembersNotFound with default headers values
func NewPostFleetsFleetIDMembersNotFound() *PostFleetsFleetIDMembersNotFound {
	return &PostFleetsFleetIDMembersNotFound{}
}

// WithPayload adds the payload to the post fleets fleet Id members not found response
func (o *PostFleetsFleetIDMembersNotFound) WithPayload(payload *models.PostFleetsFleetIDMembersNotFoundBody) *PostFleetsFleetIDMembersNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post fleets fleet Id members not found response
func (o *PostFleetsFleetIDMembersNotFound) SetPayload(payload *models.PostFleetsFleetIDMembersNotFoundBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFleetsFleetIDMembersNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFleetsFleetIDMembersUnprocessableEntityCode is the HTTP code returned for type PostFleetsFleetIDMembersUnprocessableEntity
const PostFleetsFleetIDMembersUnprocessableEntityCode int = 422

/*PostFleetsFleetIDMembersUnprocessableEntity Errors in invitation

swagger:response postFleetsFleetIdMembersUnprocessableEntity
*/
type PostFleetsFleetIDMembersUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.PostFleetsFleetIDMembersUnprocessableEntityBody `json:"body,omitempty"`
}

// NewPostFleetsFleetIDMembersUnprocessableEntity creates PostFleetsFleetIDMembersUnprocessableEntity with default headers values
func NewPostFleetsFleetIDMembersUnprocessableEntity() *PostFleetsFleetIDMembersUnprocessableEntity {
	return &PostFleetsFleetIDMembersUnprocessableEntity{}
}

// WithPayload adds the payload to the post fleets fleet Id members unprocessable entity response
func (o *PostFleetsFleetIDMembersUnprocessableEntity) WithPayload(payload *models.PostFleetsFleetIDMembersUnprocessableEntityBody) *PostFleetsFleetIDMembersUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post fleets fleet Id members unprocessable entity response
func (o *PostFleetsFleetIDMembersUnprocessableEntity) SetPayload(payload *models.PostFleetsFleetIDMembersUnprocessableEntityBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFleetsFleetIDMembersUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostFleetsFleetIDMembersInternalServerErrorCode is the HTTP code returned for type PostFleetsFleetIDMembersInternalServerError
const PostFleetsFleetIDMembersInternalServerErrorCode int = 500

/*PostFleetsFleetIDMembersInternalServerError Internal server error

swagger:response postFleetsFleetIdMembersInternalServerError
*/
type PostFleetsFleetIDMembersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.PostFleetsFleetIDMembersInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostFleetsFleetIDMembersInternalServerError creates PostFleetsFleetIDMembersInternalServerError with default headers values
func NewPostFleetsFleetIDMembersInternalServerError() *PostFleetsFleetIDMembersInternalServerError {
	return &PostFleetsFleetIDMembersInternalServerError{}
}

// WithPayload adds the payload to the post fleets fleet Id members internal server error response
func (o *PostFleetsFleetIDMembersInternalServerError) WithPayload(payload *models.PostFleetsFleetIDMembersInternalServerErrorBody) *PostFleetsFleetIDMembersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post fleets fleet Id members internal server error response
func (o *PostFleetsFleetIDMembersInternalServerError) SetPayload(payload *models.PostFleetsFleetIDMembersInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFleetsFleetIDMembersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
