package character

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/pascaldmier/esi/models"
)

// GetCharactersCharacterIDAgentsResearchReader is a Reader for the GetCharactersCharacterIDAgentsResearch structure.
type GetCharactersCharacterIDAgentsResearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCharactersCharacterIDAgentsResearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCharactersCharacterIDAgentsResearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 403:
		result := NewGetCharactersCharacterIDAgentsResearchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetCharactersCharacterIDAgentsResearchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCharactersCharacterIDAgentsResearchOK creates a GetCharactersCharacterIDAgentsResearchOK with default headers values
func NewGetCharactersCharacterIDAgentsResearchOK() *GetCharactersCharacterIDAgentsResearchOK {
	return &GetCharactersCharacterIDAgentsResearchOK{}
}

/*GetCharactersCharacterIDAgentsResearchOK handles this case with default header values.

A list of agents research information
*/
type GetCharactersCharacterIDAgentsResearchOK struct {
	/*The caching mechanism used
	 */
	CacheControl string
	/*RFC7231 formatted datetime string
	 */
	Expires string
	/*RFC7231 formatted datetime string
	 */
	LastModified string

	Payload models.GetCharactersCharacterIDAgentsResearchOKBody
}

func (o *GetCharactersCharacterIDAgentsResearchOK) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/agents_research/][%d] getCharactersCharacterIdAgentsResearchOK  %+v", 200, o.Payload)
}

func (o *GetCharactersCharacterIDAgentsResearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Cache-Control
	o.CacheControl = response.GetHeader("Cache-Control")

	// response header Expires
	o.Expires = response.GetHeader("Expires")

	// response header Last-Modified
	o.LastModified = response.GetHeader("Last-Modified")

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDAgentsResearchForbidden creates a GetCharactersCharacterIDAgentsResearchForbidden with default headers values
func NewGetCharactersCharacterIDAgentsResearchForbidden() *GetCharactersCharacterIDAgentsResearchForbidden {
	return &GetCharactersCharacterIDAgentsResearchForbidden{}
}

/*GetCharactersCharacterIDAgentsResearchForbidden handles this case with default header values.

Forbidden
*/
type GetCharactersCharacterIDAgentsResearchForbidden struct {
	Payload *models.GetCharactersCharacterIDAgentsResearchForbiddenBody
}

func (o *GetCharactersCharacterIDAgentsResearchForbidden) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/agents_research/][%d] getCharactersCharacterIdAgentsResearchForbidden  %+v", 403, o.Payload)
}

func (o *GetCharactersCharacterIDAgentsResearchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetCharactersCharacterIDAgentsResearchForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCharactersCharacterIDAgentsResearchInternalServerError creates a GetCharactersCharacterIDAgentsResearchInternalServerError with default headers values
func NewGetCharactersCharacterIDAgentsResearchInternalServerError() *GetCharactersCharacterIDAgentsResearchInternalServerError {
	return &GetCharactersCharacterIDAgentsResearchInternalServerError{}
}

/*GetCharactersCharacterIDAgentsResearchInternalServerError handles this case with default header values.

Internal server error
*/
type GetCharactersCharacterIDAgentsResearchInternalServerError struct {
	Payload *models.GetCharactersCharacterIDAgentsResearchInternalServerErrorBody
}

func (o *GetCharactersCharacterIDAgentsResearchInternalServerError) Error() string {
	return fmt.Sprintf("[GET /characters/{character_id}/agents_research/][%d] getCharactersCharacterIdAgentsResearchInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCharactersCharacterIDAgentsResearchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetCharactersCharacterIDAgentsResearchInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
