package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pascaldmier/esi/models"
)

// DeleteCharactersCharacterIDContactsNoContentCode is the HTTP code returned for type DeleteCharactersCharacterIDContactsNoContent
const DeleteCharactersCharacterIDContactsNoContentCode int = 204

/*DeleteCharactersCharacterIDContactsNoContent Contacts deleted

swagger:response deleteCharactersCharacterIdContactsNoContent
*/
type DeleteCharactersCharacterIDContactsNoContent struct {
}

// NewDeleteCharactersCharacterIDContactsNoContent creates DeleteCharactersCharacterIDContactsNoContent with default headers values
func NewDeleteCharactersCharacterIDContactsNoContent() *DeleteCharactersCharacterIDContactsNoContent {
	return &DeleteCharactersCharacterIDContactsNoContent{}
}

// WriteResponse to the client
func (o *DeleteCharactersCharacterIDContactsNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// DeleteCharactersCharacterIDContactsForbiddenCode is the HTTP code returned for type DeleteCharactersCharacterIDContactsForbidden
const DeleteCharactersCharacterIDContactsForbiddenCode int = 403

/*DeleteCharactersCharacterIDContactsForbidden Forbidden

swagger:response deleteCharactersCharacterIdContactsForbidden
*/
type DeleteCharactersCharacterIDContactsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.DeleteCharactersCharacterIDContactsForbiddenBody `json:"body,omitempty"`
}

// NewDeleteCharactersCharacterIDContactsForbidden creates DeleteCharactersCharacterIDContactsForbidden with default headers values
func NewDeleteCharactersCharacterIDContactsForbidden() *DeleteCharactersCharacterIDContactsForbidden {
	return &DeleteCharactersCharacterIDContactsForbidden{}
}

// WithPayload adds the payload to the delete characters character Id contacts forbidden response
func (o *DeleteCharactersCharacterIDContactsForbidden) WithPayload(payload *models.DeleteCharactersCharacterIDContactsForbiddenBody) *DeleteCharactersCharacterIDContactsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete characters character Id contacts forbidden response
func (o *DeleteCharactersCharacterIDContactsForbidden) SetPayload(payload *models.DeleteCharactersCharacterIDContactsForbiddenBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCharactersCharacterIDContactsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteCharactersCharacterIDContactsInternalServerErrorCode is the HTTP code returned for type DeleteCharactersCharacterIDContactsInternalServerError
const DeleteCharactersCharacterIDContactsInternalServerErrorCode int = 500

/*DeleteCharactersCharacterIDContactsInternalServerError Internal server error

swagger:response deleteCharactersCharacterIdContactsInternalServerError
*/
type DeleteCharactersCharacterIDContactsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.DeleteCharactersCharacterIDContactsInternalServerErrorBody `json:"body,omitempty"`
}

// NewDeleteCharactersCharacterIDContactsInternalServerError creates DeleteCharactersCharacterIDContactsInternalServerError with default headers values
func NewDeleteCharactersCharacterIDContactsInternalServerError() *DeleteCharactersCharacterIDContactsInternalServerError {
	return &DeleteCharactersCharacterIDContactsInternalServerError{}
}

// WithPayload adds the payload to the delete characters character Id contacts internal server error response
func (o *DeleteCharactersCharacterIDContactsInternalServerError) WithPayload(payload *models.DeleteCharactersCharacterIDContactsInternalServerErrorBody) *DeleteCharactersCharacterIDContactsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete characters character Id contacts internal server error response
func (o *DeleteCharactersCharacterIDContactsInternalServerError) SetPayload(payload *models.DeleteCharactersCharacterIDContactsInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCharactersCharacterIDContactsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
