package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostCharactersCharacterIDContactsParams creates a new PostCharactersCharacterIDContactsParams object
// with the default values initialized.
func NewPostCharactersCharacterIDContactsParams() PostCharactersCharacterIDContactsParams {
	var (
		datasourceDefault = string("tranquility")
		labelIDDefault    = int64(0)
		watchedDefault    = bool(false)
	)
	return PostCharactersCharacterIDContactsParams{
		Datasource: &datasourceDefault,

		LabelID: &labelIDDefault,

		Watched: &watchedDefault,
	}
}

// PostCharactersCharacterIDContactsParams contains all the bound params for the post characters character id contacts operation
// typically these are obtained from a http.Request
//
// swagger:parameters post_characters_character_id_contacts
type PostCharactersCharacterIDContactsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*Client identifier, takes precedence over User-Agent
	  In: header
	*/
	XUserAgent *string
	/*ID for a character
	  Required: true
	  In: path
	*/
	CharacterID int32
	/*A list of contacts to add
	  Required: true
	  Max Items: 100
	  Min Items: 1
	  In: body
	*/
	ContactIds []int32
	/*The server name you would like data from
	  In: query
	  Default: "tranquility"
	*/
	Datasource *string
	/*Add a custom label to the new contact
	  In: query
	  Default: 0
	*/
	LabelID *int64
	/*Standing for the new contact
	  Required: true
	  Maximum: 10
	  Minimum: -10
	  In: query
	*/
	Standing float32
	/*Access token to use, if preferred over a header
	  In: query
	*/
	Token *string
	/*Client identifier, takes precedence over headers
	  In: query
	*/
	UserAgent *string
	/*Whether the new contact should be watched, note this is only effective on characters
	  In: query
	  Default: false
	*/
	Watched *bool
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PostCharactersCharacterIDContactsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if err := o.bindXUserAgent(r.Header[http.CanonicalHeaderKey("X-User-Agent")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rCharacterID, rhkCharacterID, _ := route.Params.GetOK("character_id")
	if err := o.bindCharacterID(rCharacterID, rhkCharacterID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []int32
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("contactIds", "body"))
			} else {
				res = append(res, errors.NewParseError("contactIds", "body", "", err))
			}

		} else {

			if len(res) == 0 {
				o.ContactIds = body
			}
		}

	} else {
		res = append(res, errors.Required("contactIds", "body"))
	}

	qDatasource, qhkDatasource, _ := qs.GetOK("datasource")
	if err := o.bindDatasource(qDatasource, qhkDatasource, route.Formats); err != nil {
		res = append(res, err)
	}

	qLabelID, qhkLabelID, _ := qs.GetOK("label_id")
	if err := o.bindLabelID(qLabelID, qhkLabelID, route.Formats); err != nil {
		res = append(res, err)
	}

	qStanding, qhkStanding, _ := qs.GetOK("standing")
	if err := o.bindStanding(qStanding, qhkStanding, route.Formats); err != nil {
		res = append(res, err)
	}

	qToken, qhkToken, _ := qs.GetOK("token")
	if err := o.bindToken(qToken, qhkToken, route.Formats); err != nil {
		res = append(res, err)
	}

	qUserAgent, qhkUserAgent, _ := qs.GetOK("user_agent")
	if err := o.bindUserAgent(qUserAgent, qhkUserAgent, route.Formats); err != nil {
		res = append(res, err)
	}

	qWatched, qhkWatched, _ := qs.GetOK("watched")
	if err := o.bindWatched(qWatched, qhkWatched, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostCharactersCharacterIDContactsParams) bindXUserAgent(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.XUserAgent = &raw

	return nil
}

func (o *PostCharactersCharacterIDContactsParams) bindCharacterID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("character_id", "path", "int32", raw)
	}
	o.CharacterID = value

	return nil
}

func (o *PostCharactersCharacterIDContactsParams) bindDatasource(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		var datasourceDefault string = string("tranquility")
		o.Datasource = &datasourceDefault
		return nil
	}

	o.Datasource = &raw

	if err := o.validateDatasource(formats); err != nil {
		return err
	}

	return nil
}

func (o *PostCharactersCharacterIDContactsParams) validateDatasource(formats strfmt.Registry) error {

	if err := validate.Enum("datasource", "query", *o.Datasource, []interface{}{"tranquility", "singularity"}); err != nil {
		return err
	}

	return nil
}

func (o *PostCharactersCharacterIDContactsParams) bindLabelID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		var labelIdDefault int64 = int64(0)
		o.LabelID = &labelIdDefault
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("label_id", "query", "int64", raw)
	}
	o.LabelID = &value

	return nil
}

func (o *PostCharactersCharacterIDContactsParams) bindStanding(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("standing", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("standing", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertFloat32(raw)
	if err != nil {
		return errors.InvalidType("standing", "query", "float32", raw)
	}
	o.Standing = value

	if err := o.validateStanding(formats); err != nil {
		return err
	}

	return nil
}

func (o *PostCharactersCharacterIDContactsParams) validateStanding(formats strfmt.Registry) error {

	if err := validate.Minimum("standing", "query", float64(o.Standing), -10, false); err != nil {
		return err
	}

	if err := validate.Maximum("standing", "query", float64(o.Standing), 10, false); err != nil {
		return err
	}

	return nil
}

func (o *PostCharactersCharacterIDContactsParams) bindToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Token = &raw

	return nil
}

func (o *PostCharactersCharacterIDContactsParams) bindUserAgent(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.UserAgent = &raw

	return nil
}

func (o *PostCharactersCharacterIDContactsParams) bindWatched(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		var watchedDefault bool = bool(false)
		o.Watched = &watchedDefault
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("watched", "query", "bool", raw)
	}
	o.Watched = &value

	return nil
}
