package clones

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCharactersCharacterIDClonesHandlerFunc turns a function with the right signature into a get characters character id clones handler
type GetCharactersCharacterIDClonesHandlerFunc func(GetCharactersCharacterIDClonesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCharactersCharacterIDClonesHandlerFunc) Handle(params GetCharactersCharacterIDClonesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCharactersCharacterIDClonesHandler interface for that can handle valid get characters character id clones params
type GetCharactersCharacterIDClonesHandler interface {
	Handle(GetCharactersCharacterIDClonesParams, interface{}) middleware.Responder
}

// NewGetCharactersCharacterIDClones creates a new http.Handler for the get characters character id clones operation
func NewGetCharactersCharacterIDClones(ctx *middleware.Context, handler GetCharactersCharacterIDClonesHandler) *GetCharactersCharacterIDClones {
	return &GetCharactersCharacterIDClones{Context: ctx, Handler: handler}
}

/*GetCharactersCharacterIDClones swagger:route GET /characters/{character_id}/clones/ Clones getCharactersCharacterIdClones

Get clones

A list of the character's clones

---

Alternate route: `/v2/characters/{character_id}/clones/`

Alternate route: `/dev/characters/{character_id}/clones/`


---

This route is cached for up to 120 seconds

*/
type GetCharactersCharacterIDClones struct {
	Context *middleware.Context
	Handler GetCharactersCharacterIDClonesHandler
}

func (o *GetCharactersCharacterIDClones) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetCharactersCharacterIDClonesParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
