package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DeleteFleetsFleetIDSquadsSquadIDForbiddenBody delete_fleets_fleet_id_squads_squad_id_forbidden
//
// Forbidden
// swagger:model deleteFleetsFleetIdSquadsSquadIdForbiddenBody
type DeleteFleetsFleetIDSquadsSquadIDForbiddenBody struct {

	// delete_fleets_fleet_id_squads_squad_id_403_forbidden
	//
	// Forbidden message
	Error string `json:"error,omitempty"`
}

// Validate validates this delete fleets fleet Id squads squad Id forbidden body
func (m *DeleteFleetsFleetIDSquadsSquadIDForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteFleetsFleetIDSquadsSquadIDForbiddenBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteFleetsFleetIDSquadsSquadIDForbiddenBody) UnmarshalBinary(b []byte) error {
	var res DeleteFleetsFleetIDSquadsSquadIDForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
