package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetCharactersCharacterIDCalendarEventIDForbiddenBody get_characters_character_id_calendar_event_id_forbidden
//
// Forbidden
// swagger:model getCharactersCharacterIdCalendarEventIdForbiddenBody
type GetCharactersCharacterIDCalendarEventIDForbiddenBody struct {

	// get_characters_character_id_calendar_event_id_403_forbidden
	//
	// Forbidden message
	Error string `json:"error,omitempty"`
}

// Validate validates this get characters character Id calendar event Id forbidden body
func (m *GetCharactersCharacterIDCalendarEventIDForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GetCharactersCharacterIDCalendarEventIDForbiddenBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetCharactersCharacterIDCalendarEventIDForbiddenBody) UnmarshalBinary(b []byte) error {
	var res GetCharactersCharacterIDCalendarEventIDForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
