package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetCorporationsCorporationIDStructuresOKBodyItemsCurrentVul get_corporations_corporation_id_structures_current_vul
//
// This week's vulnerability windows, Monday is day 0
// swagger:model getCorporationsCorporationIdStructuresOKBodyItemsCurrentVul
type GetCorporationsCorporationIDStructuresOKBodyItemsCurrentVul []*GetCorporationsCorporationIDStructuresOKBodyItemsCurrentVulItems

// Validate validates this get corporations corporation Id structures o k body items current vul
func (m GetCorporationsCorporationIDStructuresOKBodyItemsCurrentVul) Validate(formats strfmt.Registry) error {
	var res []error

	iGetCorporationsCorporationIDStructuresOKBodyItemsCurrentVulSize := int64(len(m))

	if err := validate.MaxItems("", "body", iGetCorporationsCorporationIDStructuresOKBodyItemsCurrentVulSize, 168); err != nil {
		return err
	}

	for i := 0; i < len(m); i++ {

		if swag.IsZero(m[i]) { // not required
			continue
		}

		if m[i] != nil {

			if err := m[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName(strconv.Itoa(i))
				}
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
