package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostUIOpenwindowInformationForbiddenBody post_ui_openwindow_information_forbidden
//
// Forbidden
// swagger:model postUiOpenwindowInformationForbiddenBody
type PostUIOpenwindowInformationForbiddenBody struct {

	// post_ui_openwindow_information_403_forbidden
	//
	// Forbidden message
	Error string `json:"error,omitempty"`
}

// Validate validates this post Ui openwindow information forbidden body
func (m *PostUIOpenwindowInformationForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostUIOpenwindowInformationForbiddenBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostUIOpenwindowInformationForbiddenBody) UnmarshalBinary(b []byte) error {
	var res PostUIOpenwindowInformationForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
