package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostCharactersAffiliationUnprocessableEntityBody post_characters_affiliation_unprocessable_entity
//
// Unprocessable entity
// swagger:model postCharactersAffiliationUnprocessableEntityBody
type PostCharactersAffiliationUnprocessableEntityBody struct {

	// post_characters_affiliation_422_unprocessable_entity
	//
	// Unprocessable entity message
	Error string `json:"error,omitempty"`
}

// Validate validates this post characters affiliation unprocessable entity body
func (m *PostCharactersAffiliationUnprocessableEntityBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostCharactersAffiliationUnprocessableEntityBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCharactersAffiliationUnprocessableEntityBody) UnmarshalBinary(b []byte) error {
	var res PostCharactersAffiliationUnprocessableEntityBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
