package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostCharactersCharacterIDFittingsInternalServerErrorBody post_characters_character_id_fittings_internal_server_error
//
// Internal server error
// swagger:model postCharactersCharacterIdFittingsInternalServerErrorBody
type PostCharactersCharacterIDFittingsInternalServerErrorBody struct {

	// post_characters_character_id_fittings_500_internal_server_error
	//
	// Internal server error message
	Error string `json:"error,omitempty"`
}

// Validate validates this post characters character Id fittings internal server error body
func (m *PostCharactersCharacterIDFittingsInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostCharactersCharacterIDFittingsInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCharactersCharacterIDFittingsInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PostCharactersCharacterIDFittingsInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
