package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PutCorporationsCorporationIDStructuresStructureIDInternalServerErrorBody put_corporations_corporation_id_structures_structure_id_internal_server_error
//
// Internal server error
// swagger:model putCorporationsCorporationIdStructuresStructureIdInternalServerErrorBody
type PutCorporationsCorporationIDStructuresStructureIDInternalServerErrorBody struct {

	// put_corporations_corporation_id_structures_structure_id_500_internal_server_error
	//
	// Internal server error message
	Error string `json:"error,omitempty"`
}

// Validate validates this put corporations corporation Id structures structure Id internal server error body
func (m *PutCorporationsCorporationIDStructuresStructureIDInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PutCorporationsCorporationIDStructuresStructureIDInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PutCorporationsCorporationIDStructuresStructureIDInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PutCorporationsCorporationIDStructuresStructureIDInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
